const task = [
    {
        "id": "N-0076",
        "title": "TODAY",
        "description": "no description",
        "subTask": [
            {
                "id": 1734686965598,
                "content": "Add customize list style for number/sub section",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 1734686967790,
                "content": "Add \"codeSimple\" list style",
                "completed": true,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 15,
                "content": "Fix Linkedin",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 16,
                "content": "Fix Resume and make a Portofolio",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 8,
                "content": "Displayed Projects",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 1
            },
            {
                "id": 9,
                "content": "[FINISH] justRUN! Game",
                "completed": true,
                "listStyle": "plus",
                "indent": 2
            },
            {
                "id": 1734449270393,
                "content": "[FINISH] PeakTime Cloud Architecture",
                "completed": true,
                "listStyle": "plus",
                "indent": 2
            },
            {
                "id": 11,
                "content": "[FINISH] PeakTime",
                "completed": true,
                "listStyle": "plus",
                "indent": 2
            },
            {
                "id": 1734420559368,
                "content": "[FINISH] Todo Website",
                "completed": true,
                "listStyle": "plus",
                "indent": 2
            },
            {
                "id": 1734420583201,
                "content": "[FINISH] Restaurant Recommendation Website",
                "completed": true,
                "listStyle": "plus",
                "indent": 2
            },
            {
                "id": 1734423204431,
                "content": "[FINISH] Quiz Web",
                "completed": true,
                "listStyle": "plus",
                "indent": 2
            },
            {
                "id": 10,
                "content": "[REWORK] Jemanten",
                "completed": false,
                "listStyle": "plus",
                "indent": 2
            },
            {
                "id": 1734420751736,
                "content": "[REWORK] Resume Website",
                "completed": false,
                "listStyle": "plus",
                "indent": 2
            },
            {
                "id": 12,
                "content": "[NEW] Portofolio Website",
                "completed": false,
                "listStyle": "plus",
                "indent": 2
            },
            {
                "id": 1734422526426,
                "content": "https://wpriverthemes.com/HTML/drake/home6.html#home",
                "completed": false,
                "listStyle": "link",
                "indent": 3
            },
            {
                "id": 1734422908545,
                "content": "https://preview.themeforest.net/item/bentox-personal-portfolio-html-templates/full_screen_preview/50513423?_ga=2.246856452.1454913207.1734422329-1566479235.1734422329",
                "completed": false,
                "listStyle": "link",
                "indent": 3
            },
            {
                "id": 1734422912725,
                "content": "https://harnishdesign.net/demo/react/callum/demo/?theme=Full%20Screen%20Menu&intro=default",
                "completed": false,
                "listStyle": "link",
                "indent": 3
            },
            {
                "id": 1734425331359,
                "content": "https://github.com/chetanverma16/react-portfolio-template?tab=readme-ov-file",
                "completed": false,
                "listStyle": "link",
                "indent": 3
            },
            {
                "id": 1734420622624,
                "content": "[NEW] Archive Akademik Website",
                "completed": false,
                "listStyle": "plus",
                "indent": 2
            },
            {
                "id": 1734420662169,
                "content": "[NEW] Money Tracker Website",
                "completed": false,
                "listStyle": "plus",
                "indent": 2
            },
            {
                "id": 17,
                "content": "Apply to all internship as much as possible",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 4,
                "content": "Focus on Web-Dev",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 5,
                "content": "Rework The Thesis",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 6,
                "content": "More research on the method being used ",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 1
            },
            {
                "id": 7,
                "content": "Research about the model architecture",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 1
            }
        ],
        "completed": false,
        "priority": false,
        "schedule": true,
        "scheduleType": "[D]",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "00:01",
        "deadlineEndTime": "23:59",
        "tags": []
    },
    {
        "id": "N-0074",
        "title": "Current Priority",
        "description": "no description",
        "subTask": [
            {
                "id": 0,
                "content": "Classes",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 1,
                "content": "NLP -> Presentasi",
                "completed": true,
                "listStyle": "checkbox",
                "indent": 1
            },
            {
                "id": 2,
                "content": "PCD -> Presentasi",
                "completed": true,
                "listStyle": "checkbox",
                "indent": 1
            },
            {
                "id": 3,
                "content": "RPP -> Laporan Akhir",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 1
            },
            {
                "id": 4,
                "content": "PKL",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 5,
                "content": "MicroData -> Confirmed 6th January 2025",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 1
            },
            {
                "id": 6,
                "content": "DBS Foundation -> Find a way to get recommendation letter before 30th January",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 1
            },
            {
                "id": 1734508445889,
                "content": "ASDF.ID -> Wait for response",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 1
            },
            {
                "id": 10,
                "content": "EdTech Backend Developer -> wait for email",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 1
            },
            {
                "id": 7,
                "content": "Other -> wait for email",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 1
            },
            {
                "id": 8,
                "content": "Thesis -> Take project hibah next semester, get pak Radhinka one if possible",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 9,
                "content": "Fullstack Development -> Finish that odin project you dipshit",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            }
        ],
        "completed": false,
        "priority": true,
        "schedule": false,
        "scheduleType": "",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "noDeadlineStartTime",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    },
    {
        "id": "N-0069",
        "title": "Expense Tracker PWA",
        "description": "no description",
        "subTask": [
            {
                "id": 0,
                "content": "Set up budget each month",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 1,
                "content": "Form to put my expense consist of name, money spend, the date of expense, category (ex: food, primary, transportation, etc), createdAt",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 2,
                "content": "Count the budget left out of setup budget that month",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 3,
                "content": "Stats f spending each month, and display the percentage of each spending out of the total budget",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 4,
                "content": "Icon based on the category that listed",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 5,
                "content": "Projection of future spending based on the pattern of spending the last 5 days and warning if its gonna over budget",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 6,
                "content": "Spending of each day/month displayed like a receipt",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            }
        ],
        "completed": false,
        "priority": false,
        "schedule": false,
        "scheduleType": "",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "noDeadlineStartTime",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    },
    {
        "id": "N-0067",
        "title": "Find Internship",
        "description": "no description",
        "subTask": [
            {
                "id": 0,
                "content": "DBS Foundation Program",
                "completed": false,
                "listStyle": "plus",
                "indent": 0
            },
            {
                "id": 1,
                "content": "PT Mikrodata",
                "completed": true,
                "listStyle": "plus",
                "indent": 0
            }
        ],
        "completed": false,
        "priority": true,
        "schedule": false,
        "scheduleType": "",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "noDeadlineStartTime",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    },
    {
        "id": "N-0059",
        "title": " IDCamp and Project Odin",
        "description": "no description",
        "subTask": [
            {
                "id": 0,
                "content": "Archive Akademik -> React.js Node.js PostGre-SQL-etc",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 1,
                "content": "Project Display -> React.js",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 2,
                "content": "Re-work Past Project -> React.js",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 3,
                "content": "Finance Tracker",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            }
        ],
        "completed": false,
        "priority": true,
        "schedule": false,
        "scheduleType": "",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "noDeadlineStartTime",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    },
    {
        "id": "N-0056",
        "title": " Finish TA",
        "description": "no description",
        "subTask": [
            {
                "id": 0,
                "content": "Bab I",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 1734580789174,
                "content": "Kalau mau membandingkan sebuah metode, pada bagian penting jangan setelah itu ada penggunaan metode yang tidak seimbang, jangan satu dipake satu tidak",
                "completed": false,
                "listStyle": "plus",
                "indent": 1
            },
            {
                "id": 1734581216855,
                "content": "Penggambaran alur jangan asal",
                "completed": false,
                "listStyle": "plus",
                "indent": 1
            },
            {
                "id": 1734582141936,
                "content": "Perbandingan metode harus apple to apple, dimana ada aspek ya g memang bisa dibandingkan jangan sampai membandingkan sesuatu yang sudah jelas atau yang merupakan kelemahan dan kelebihan satu metode",
                "completed": false,
                "listStyle": "plus",
                "indent": 1
            },
            {
                "id": 1,
                "content": "Bab II",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 2,
                "content": "Bab III",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 3,
                "content": "Bab Lampiran",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 1734580640064,
                "content": "PPT SemPro",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 0
            },
            {
                "id": 1734580660222,
                "content": "Latar Belakang",
                "completed": false,
                "listStyle": "checkbox",
                "indent": 1
            }
        ],
        "completed": false,
        "priority": false,
        "schedule": false,
        "scheduleType": "",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "noDeadlineStartTime",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    },
    {
        "id": "N-0055",
        "title": "Alternatif Judul TA",
        "description": "no description",
        "subTask": [
            {
                "id": 0,
                "content": "Klasifikasi Pola Batik CNN.",
                "completed": false,
                "listStyle": "plus",
                "indent": 0
            },
            {
                "id": 1,
                "content": "Klasifikasi Karya Museum CNN.",
                "completed": false,
                "listStyle": "plus",
                "indent": 0
            },
            {
                "id": 2,
                "content": "Klasifikasi Kekuatan Tanah Pondasi CNN.",
                "completed": false,
                "listStyle": "plus",
                "indent": 0
            },
            {
                "id": 3,
                "content": "Klasifikasi Nilai Uang",
                "completed": false,
                "listStyle": "plus",
                "indent": 0
            },
            {
                "id": 1734585568231,
                "content": "Permasalahkan bagian kesamaan karakteristik uang seperti ukuran ketebalan, warna sehingga metode lama pada mesin lebih buruk",
                "completed": false,
                "listStyle": "plus",
                "indent": 1
            },
            {
                "id": 1734581584376,
                "content": "Multi input model CNN dengan citra dan multi feature",
                "completed": false,
                "listStyle": "plus",
                "indent": 1
            },
            {
                "id": 1734581621518,
                "content": "Penggunaan Hyper parameter, pada feature",
                "completed": false,
                "listStyle": "plus",
                "indent": 1
            },
            {
                "id": 4,
                "content": "Klasifikasi Aksara/Alfabet yang ada di Indonesi.",
                "completed": false,
                "listStyle": "plus",
                "indent": 0
            }
        ],
        "completed": false,
        "priority": false,
        "schedule": false,
        "scheduleType": "",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "noDeadlineStartTime",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    }
];

export const completedData = [
    {
        "id": "N-0077",
        "title": "Resume Jurnal Segmentasi PCD",
        "description": "no description",
        "subTask": [],
        "completed": true,
        "priority": false,
        "schedule": true,
        "scheduleType": "[A]",
        "deadlineStartDate": "2024-12-13",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "23:59",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    },
    {
        "id": "N-0062",
        "title": "Pengolahan Bahasa Alami",
        "description": "Kelas R | GK2-312 A | WIY",
        "subTask": [],
        "completed": true,
        "priority": false,
        "schedule": true,
        "scheduleType": "[W]",
        "deadlineStartDate": "Monday",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "09:30",
        "deadlineEndTime": "12:00",
        "tags": []
    },
    {
        "id": "N-0061",
        "title": "Pengolahan Citra Digital",
        "description": "Kelas RA | Labkom 3 Labtek 1 Lt 3 | ANS",
        "subTask": [],
        "completed": true,
        "priority": false,
        "schedule": true,
        "scheduleType": "[W]",
        "deadlineStartDate": "Friday",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "09:30",
        "deadlineEndTime": "12:00",
        "tags": []
    },
    {
        "id": "N-0060",
        "title": "Representasi Pengetahuan dan Penalaran",
        "description": "Kelas R | LAB IOT | MCU",
        "subTask": [],
        "completed": true,
        "priority": false,
        "schedule": true,
        "scheduleType": "[W]",
        "deadlineStartDate": "Friday",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "13:00",
        "deadlineEndTime": "15:30",
        "tags": []
    },
    {
        id: "N-0075",
        title: "Notulen PCD - 05/12/24",
        description: "no description",
        subTask: [
            {
                id: 0,
                content:
                    "Tabel Profile Kesamping, tapi kolom dijadikan 5 aja -> 1 per anggota, Foto diatas dibawahnya nama NIM",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 1,
                content:
                    "Confusion Matrix -> lengkapi bagian recall, precision, dan f1-score",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 2,
                content:
                    "Preprocessing, Augmentasi Data, bagian model training-evaluation, dan prediction display masuk ke dalam sub-bab arsitektur sistem",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 3,
                content:
                    "Sub-bab metode pengembangan dan pengujian dimasukkan ke sub-bab arsitektur sistem lalu didalam sub-bab metode tadi dimasukkan bagian-bagian diatas tadi",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 4,
                content: "Arsitektur Sistem",
                completed: false,
                listStyle: "plus",
                indent: 1,
            },
            {
                id: 5,
                content: "Metode Pengembangan",
                completed: false,
                listStyle: "plus",
                indent: 2,
            },
            {
                id: 6,
                content: "Augmentasi, Data Preprocessing, dll",
                completed: false,
                listStyle: "plus",
                indent: 3,
            },
            {
                id: 7,
                content: "Metode Pengujian",
                completed: false,
                listStyle: "plus",
                indent: 2,
            },
            {
                id: 8,
                content: "Confusion Matrix",
                completed: false,
                listStyle: "plus",
                indent: 3,
            },
            {
                id: 10,
                content:
                    "Metodologi pengumpulan dataset diletakkan sebelum alat dan bahan",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 11,
                content:
                    "Bab IV -> jelasin mengenai labeling, library yang dipakai untuk apa saja, untuk penjelasan kode fokus ke penjelasan fitur/fungsi secara keseluruhan bukan kode per baris",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 12,
                content:
                    "Buat ngejelasin kode jangan pake screenshoot tapi copy lalu display pada table dan pakai code-formatter web",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 13,
                content: "https://www.syntax-highlighter.dev/",
                completed: false,
                listStyle: "link",
                indent: 1,
            },
            {
                id: 14,
                content: "https://highlight.hohli.com/",
                completed: false,
                listStyle: "link",
                indent: 1,
            },
            {
                id: 15,
                content:
                    "Kesimpulan nanti fokus pada menjawab pertanyaan pada Rumusan Masalah",
                completed: false,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 16,
                content: "PPT gak perlu, presentasi pake laporan sama demo kode saja",
                completed: false,
                listStyle: "checkbox",
                indent: 0,
            },
        ],
        completed: true,
        priority: false,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0072",
        title: "PCD Capstone Project",
        description: "no description",
        subTask: [
            {
                id: 0,
                content: "Tingkatin Kontras Clache",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 1,
                content: "Hue bermasalah karena jadinya merah range 0-30 entah kenapa",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 2,
                content: "GLCM untuk tekstur, contrast, energy nya low, correlation, ",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 3,
                content:
                    "dataset di sift mana yang jelek atau bagus, pembagian otomatis bermasalah",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 4,
                content:
                    "input model ada 2 (gambar dikecilin, dan dinormalisasi eg dibagi 255) feature texture sama feature warna sama gambarnya",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 5,
                content:
                    "hasil model overfitting, akurasi 100% tapi validasi 75%, value loss dapat 1 tapi bagusnya dibawah 1",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 6,
                content:
                    "Masalah: ekstrasi fitur malah fokus ke background, tekstur uang gak ke detect terutama yang jarak jauh, susunan dataset harus dibalance",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 7,
                content:
                    "hasil epochs gak stabil naik turun, harusnya stabil naik dikit2",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
            {
                id: 8,
                content: "Isi2 laporan",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0071",
        title: "Sekawan Media Internship Technical Test",
        description: "no description",
        subTask: [
            {
                id: 0,
                content:
                    "Use Open API for Restaurant Data like Yelp, Zomato API, OpenCage Geocoder API",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
            { id: 1, content: "Main", completed: true, listStyle: "plus", indent: 0 },
            {
                id: 2,
                content: "Filter navigation",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 3,
                content: "Open now (client side filter)",
                completed: true,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 4,
                content: "Price (client side filter)",
                completed: true,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 5,
                content: "Categories/Cuisines (server side search filter)",
                completed: true,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 6,
                content: "Section",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 7,
                content: "Restaurant item",
                completed: true,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 8,
                content: "Image (use first item in `photos`)",
                completed: true,
                listStyle: "checkbox",
                indent: 3,
            },
            {
                id: 9,
                content: "Cuisine / Categories (use first item in `categories`)",
                completed: true,
                listStyle: "checkbox",
                indent: 3,
            },
            {
                id: 10,
                content: "Rating",
                completed: true,
                listStyle: "checkbox",
                indent: 3,
            },
            {
                id: 11,
                content: "Price range",
                completed: true,
                listStyle: "checkbox",
                indent: 3,
            },
            {
                id: 12,
                content: "Open / Closed",
                completed: true,
                listStyle: "checkbox",
                indent: 3,
            },
            {
                id: 13,
                content: "Restaurant name",
                completed: true,
                listStyle: "checkbox",
                indent: 3,
            },
            {
                id: 14,
                content: "Learn more (navigate to Detail View)",
                completed: true,
                listStyle: "checkbox",
                indent: 3,
            },
            {
                id: 15,
                content: "Detail View",
                completed: true,
                listStyle: "plus",
                indent: 1,
            },
            {
                id: 16,
                content: "Restaurant Name & Rating",
                completed: true,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 17,
                content: "Map (optional)",
                completed: true,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 18,
                content: "Section",
                completed: true,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 19,
                content: "Review item",
                completed: true,
                listStyle: "checkbox",
                indent: 3,
            },
            {
                id: 20,
                content: "Image",
                completed: true,
                listStyle: "checkbox",
                indent: 4,
            },
            {
                id: 21,
                content: "Name",
                completed: true,
                listStyle: "checkbox",
                indent: 4,
            },
            {
                id: 22,
                content: "Rating",
                completed: true,
                listStyle: "checkbox",
                indent: 4,
            },
            {
                id: 23,
                content: "Text",
                completed: true,
                listStyle: "checkbox",
                indent: 4,
            },
        ],
        completed: true,
        priority: false,
        schedule: true,
        scheduleType: "[A]",
        deadlineStartDate: "2024-11-22",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "11:00",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0068",
        title: "Update Todo App 3",
        description: "no description",
        subTask: [
            {
                id: 0,
                content: "Category Badge",
                completed: false,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 1,
                content: "Subtask Completion Percentage",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 2,
                content: "Preferred ID",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0066",
        title: "Update Todo App 2",
        description: "no description",
        subTask: [
            {
                id: 0,
                content: "Typescript",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 1,
                content: "Bootstrap",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 2,
                content: "Stats Progress Bar",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 3,
                content: "Form and Label",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 4,
                content: "Badge",
                completed: false,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 5,
                content: "Toggles",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 6,
                content: "Validation",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 7,
                content: "Modal for Delete Validation",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 8,
                content:
                    "Counter for Schedule item if not completed for scheduleType [D], [W], [Y]",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0065",
        title: "Tanya Soal PKL di DBS Foundation Program",
        description: "no description",
        subTask: [
            {
                id: 0,
                content: "Minta nomor ibu leslie",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 1,
                content: "Apakah program DBS Foundation bisa dikonversikan ke PKL",
                completed: false,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 2,
                content:
                    "Untuk Laporan PKL apakah menjadi semester 9, dan apakah pada semester 8 dapat mengerjakan TA1 dan TA2",
                completed: false,
                listStyle: "plus",
                indent: 0,
            },
        ],
        completed: true,
        priority: false,
        schedule: true,
        scheduleType: "[S]",
        deadlineStartDate: "2024-11-18",
        deadlineEndDate: "2024-11-22",
        deadlineStartTime: "09:00",
        deadlineEndTime: "16:00",
        tags: [],
    },
    {
        id: "N-0064",
        title: "Update Todo App",
        description: "no description",
        subTask: [
            {
                id: 0,
                content: "Add deadlineStartDate",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 1,
                content: "Add deadlineStartTime",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 2,
                content: "Add deadlineEndDate",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 3,
                content: "Add deadlineEndTime",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 4,
                content:
                    'On Schedule List have a more specific listing per day on that week and shows the date on that week from Monday to Sunday and "coming soon" for the date that out of the week',
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0063",
        title: "RPP Research Project",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0058",
        title: " Find Internship",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0057",
        title: "NLP Capstone Project",
        description: "no description",
        subTask: [
            {
                id: 0,
                content: "Cari kode buat chatbot dulu, nunggu preprocessing",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 1,
                content: "Modeling LSTM",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0054",
        title: "Feature Test (Thursday, 31-10-24)",
        description: "Pengetesan fitur todo.",
        subTask: [
            {
                id: 0,
                content: "List Style +/-",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
            {
                id: 1,
                content: "Sub 1",
                completed: false,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 2,
                content: "Sub 1.1",
                completed: false,
                listStyle: "plus",
                indent: 1,
            },
            {
                id: 3,
                content: "Sub 1.1.1",
                completed: true,
                listStyle: "plus",
                indent: 2,
            },
            {
                id: 4,
                content: "Sub 1.1.2",
                completed: true,
                listStyle: "plus",
                indent: 2,
            },
            {
                id: 5,
                content: "Sub 1.2",
                completed: false,
                listStyle: "plus",
                indent: 1,
            },
            {
                id: 6,
                content: "Sub 1.2.1",
                completed: true,
                listStyle: "plus",
                indent: 2,
            },
            {
                id: 7,
                content: "List Style Checkbox",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
            {
                id: 8,
                content: "Sub 2",
                completed: false,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 9,
                content: "Sub 2.1",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 10,
                content: "Sub 2.1.1",
                completed: false,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 11,
                content: "Sub 2.1.2",
                completed: true,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 12,
                content: "Sub 2.2",
                completed: false,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 13,
                content: "Sub 2.2.1",
                completed: true,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 14,
                content: "List XMarkCircle",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
            {
                id: 15,
                content: "Sub 3",
                completed: true,
                listStyle: "xcircle",
                indent: 0,
            },
            {
                id: 16,
                content: "Sub 3.1",
                completed: false,
                listStyle: "xcircle",
                indent: 1,
            },
            {
                id: 17,
                content: "Sub 3.1.1",
                completed: true,
                listStyle: "xcircle",
                indent: 2,
            },
            {
                id: 18,
                content: "Sub 3.1.2",
                completed: false,
                listStyle: "xcircle",
                indent: 2,
            },
            {
                id: 19,
                content: "Sub 3.2",
                completed: false,
                listStyle: "xcircle",
                indent: 1,
            },
            {
                id: 20,
                content: "Sub 3.2.1",
                completed: true,
                listStyle: "xcircle",
                indent: 2,
            },
            {
                id: 21,
                content: "Sekian dan Terima Gaji.",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
            {
                id: 22,
                content: "Sub 4",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 23,
                content: "Desc Sub 4",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
            {
                id: 24,
                content: "Sub 4.1",
                completed: false,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 25,
                content: "Desc Sub 4.1",
                completed: false,
                listStyle: "text",
                indent: 1,
            },
            {
                id: 26,
                content: "Sub 4.1.1",
                completed: true,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 27,
                content: "Desc Sub 4.1.1",
                completed: false,
                listStyle: "text",
                indent: 2,
            },
        ],
        completed: true,
        priority: false,
        schedule: true,
        scheduleType: "[A]",
        deadlineStartDate: "2024-10-31",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "23:59",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0053",
        title: "Feature Test (Thursday, 31-10-24)",
        description: "Pengetesan fitur todo.",
        subTask: [
            {
                id: 0,
                content: "List Style +/-",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
            {
                id: 1,
                content: "Sub 1",
                completed: false,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 2,
                content: "Sub 1.1",
                completed: false,
                listStyle: "plus",
                indent: 1,
            },
            {
                id: 3,
                content: "Sub 1.1.1",
                completed: false,
                listStyle: "plus",
                indent: 2,
            },
            {
                id: 4,
                content: "Sub 1.1.2",
                completed: false,
                listStyle: "plus",
                indent: 2,
            },
            {
                id: 5,
                content: "Sub 1.2",
                completed: false,
                listStyle: "plus",
                indent: 1,
            },
            {
                id: 6,
                content: "Sub 1.2.1",
                completed: false,
                listStyle: "plus",
                indent: 2,
            },
            {
                id: 7,
                content: "List Style Checkbox",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
            {
                id: 8,
                content: "Sub 2",
                completed: false,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 9,
                content: "Sub 2.1",
                completed: false,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 10,
                content: "Sub 2.1.1",
                completed: false,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 11,
                content: "Sub 2.1.2",
                completed: false,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 12,
                content: "Sub 2.2",
                completed: false,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 13,
                content: "Sub 2.2.1",
                completed: false,
                listStyle: "checkbox",
                indent: 2,
            },
            {
                id: 14,
                content: "List XMarkCircle",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
            {
                id: 15,
                content: "Sub 3",
                completed: false,
                listStyle: "xcircle",
                indent: 0,
            },
            {
                id: 16,
                content: "Sub 3.1",
                completed: false,
                listStyle: "xcircle",
                indent: 1,
            },
            {
                id: 17,
                content: "Sub 3.1.1",
                completed: false,
                listStyle: "xcircle",
                indent: 2,
            },
            {
                id: 18,
                content: "Sub 3.1.2",
                completed: false,
                listStyle: "xcircle",
                indent: 2,
            },
            {
                id: 19,
                content: "Sub 3.2",
                completed: false,
                listStyle: "xcircle",
                indent: 1,
            },
            {
                id: 20,
                content: "Sub 3.2.1",
                completed: false,
                listStyle: "xcircle",
                indent: 2,
            },
            {
                id: 21,
                content: "Sekian dan Terima Gaji.",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
        ],
        completed: true,
        priority: false,
        schedule: true,
        scheduleType: "[A]",
        deadlineStartDate: "2024-10-31",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "23:59",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0052",
        title: "Todo React App",
        description: "no description",
        subTask: [
            {
                id: 0,
                content: "New Todo Form Modal.",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 1,
                content:
                    "There is paste button that automaticaly fill the three input text.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 2,
                content: "Display of date and clock.",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 3,
                content: "Take care of checkboxes in description.",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 4,
                content: "Major DEL, PUT, and GET feature.",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 5,
                content: "Fix the styling.",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 6,
                content: "Maybe has an option of want color or monochrome.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 7,
                content:
                    "Sorting the localStorage save based on the last 4 digit of the id from bigger to smallest.",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 8,
                content: "Fix the id assign system to the last item + 1.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
        ],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0051",
        title: "DOT Internship (dl: 13-10-24)",
        description: "no description",
        subTask: [
            {
                id: 0,
                content: "Web React Kuis.",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 1,
                content: "Video Demo Web.",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "2024-10-13",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "23:59",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0050",
        title: "Jumat, 18-10-24 15:00-17:00",
        description: "Representasi dan Penalaran.",
        subTask: [
            {
                id: 0,
                content: "GK1.203.",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: true,
        scheduleType: "[UTS]",
        deadlineStartDate: "2024-10-18",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "15:00",
        deadlineEndTime: "17:00",
        tags: [],
    },
    {
        id: "N-0049",
        title: "Jumat, 18-10-24 09:30-11:30",
        description: "Pengolahan Citra Digital.",
        subTask: [
            {
                id: 0,
                content: "GK1.406A.",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: true,
        scheduleType: "[UTS]",
        deadlineStartDate: "2024-10-18",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "09:30",
        deadlineEndTime: "11:30",
        tags: [],
    },
    {
        id: "N-0048",
        title: "Senin, 14-10-24 10:00-12:00",
        description: "Pengolahan Bahasa Alami.",
        subTask: [],
        completed: true,
        priority: true,
        schedule: true,
        scheduleType: "[UTS]",
        deadlineStartDate: "2024-10-14",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "10:00",
        deadlineEndTime: "12:00",
        tags: [],
    },
    {
        id: "N-0047",
        title: "Sabtu, 12-10-24 Tugas 3 PCD",
        description: "no description",
        subTask: [
            {
                id: 0,
                content: "Tulis tangan.",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 1,
                content: "Soal Konvolusi.",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 2,
                content: "Histogram.",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: true,
        scheduleType: "[A]",
        deadlineStartDate: "2024-10-12",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "23:59",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0046",
        title: "Jumat, 11-10-24 Tugas 2 PCD",
        description: "no description",
        subTask: [
            {
                id: 0,
                content: "Operasi Aras Titik:",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 1,
                content: "Konversi Grayscale.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 2,
                content: "Thresholding.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 3,
                content: "Konversi Citra Negatif.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 4,
                content: "Pencerahan.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 5,
                content: "Operasi Aritmatika:",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 6,
                content: "Penjumlahan Antar 2 Citra.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 7,
                content: "Pengurangan Antar 2 Citra.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 8,
                content: "Perkalian Antar 2 Citra.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 9,
                content: "Operasi Boolean:",
                completed: true,
                listStyle: "plus",
                indent: 0,
            },
            {
                id: 10,
                content: "AND.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 11,
                content: "OR.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 12,
                content: "NOT.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
            {
                id: 13,
                content: "XOR.",
                completed: true,
                listStyle: "checkbox",
                indent: 1,
            },
        ],
        completed: true,
        priority: true,
        schedule: true,
        scheduleType: "[A]",
        deadlineStartDate: "2024-10-11",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "23:59",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0045",
        title: "Rabu, 09-10-24 Tugas RPP",
        description: "no description",
        subTask: [
            {
                id: 0,
                content: "Perluas Semantik.",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 1,
                content: "Jadikan Frame.",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "2024-10-09",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "23:59",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0044",
        title: "Todo Update",
        description: "no description",
        subTask: [
            {
                id: 0,
                content:
                    "Make if list style followed by double dot or more means more indent or second rate.",
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
            {
                id: 1,
                content: 'Make so if ":." is for start of list.',
                completed: true,
                listStyle: "checkbox",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0043",
        title: "Jumat, 9:30-12:00",
        description: "Pengolahan Citra Digital",
        subTask: [
            {
                id: 0,
                content: "Kelas RA | GK2-112 A | ANS",
                completed: false,
                listStyle: "text",
                indent: 0,
            },
        ],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0042",
        title: 'add "Today!" for schedule todo',
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0041",
        title: 'Make details on todo feature => using "',
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0040",
        title:
            "For print saves, has an option of what feature save you want extract",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0039",
        title: "add number of history per tab maybe",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0038",
        title: "history tab look like book index page",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0037",
        title: "Floating action button on mobile",
        description: "no description",
        subTask: [],
        completed: true,
        priority: false,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0036",
        title: "Make input dialog to applied the saved settings",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0035",
        title: "Print all current settings and saved todo item into stringify json",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0034",
        title: "Save last played of each Tab",
        description: "no description",
        subTask: [],
        completed: true,
        priority: false,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0033",
        title: "Save MP3 Settings",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0032",
        title: ":last-child border",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0031",
        title: "CSS Accent Color",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0030",
        title: "Add more item to font and theme on theme popover",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0029",
        title: "Fix Theme Popover For Socials Footer",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0028",
        title: "Fix Theme Popover For Mobile",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0027",
        title: "Theme Popover",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0026",
        title: "Font Option Popover",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0025",
        title: "QR Popover",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0024",
        title: "Try new things from fireship",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0023",
        title: "Cover Doctype Slider",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0022",
        title: "coverChangeInterval Slider",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0021",
        title: "Audio Speed Slider",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0020",
        title: "Jump Seconds Slider",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0019",
        title: "Multiple Theme Option",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0018",
        title: "if clicked speker button",
        description:
            "slider show up under duration slider and changes depend on the level of volume, speaker icon changes",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0017",
        title: "Volume setting in 10 level",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0016",
        title:
            "Queue Tab and Podcasts Tab both are dynamically added so it needs special function",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0015",
        title: "Fix Play From Queue Problem",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0014",
        title: "Fix Podcast Problem",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0013",
        title: "Shuffle, Repeat, Normal, Reverse Button Functions",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0012",
        title: "Update Volume Slider Function",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0011",
        title: "Update Slider Max and Value Function",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0010",
        title: "Display Metadata on Mp3 Player Function",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0009",
        title: "Make a function",
        description:
            "that parameter is the list id, url and based on the input id gonna go on a ifelse to load the list display it on queue list like loadResult function",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0008",
        title:
            "Make a function to extract the mp3 duration and display it on my cli",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0007",
        title: "Make the song yml to json format",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0006",
        title: "Make a Function to Get a Tab ID and The Mp3 Link",
        description:
            "There is gonna be an ifelse to determine the tab then through loop finding the url == songurl",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0005",
        title: "Established a Global List For Currently Played List",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0004",
        title: "Tab on MP3 Player to Show Current Running Queue",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0003",
        title: "Rebuild MP3 Player Functions Properly",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0002",
        title: "Change The Duration Slider",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
    {
        id: "N-0001",
        title: "PWA",
        description: "no description",
        subTask: [],
        completed: true,
        priority: true,
        schedule: false,
        scheduleType: "",
        deadlineStartDate: "noDeadlineStartDate",
        deadlineEndDate: "noDeadlineEndDate",
        deadlineStartTime: "noDeadlineStartTime",
        deadlineEndTime: "noDeadlineEndTime",
        tags: [],
    },
];


export const instructionData = [
    {
        "id": "I-0001",
        "title": "How to start a React.js project ?",
        "description": "no description",
        "subTask": [
            {
                "id": 0,
                "content": "1. Create Vite, React.js, Typescript directories",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 1734685036159,
                "content": "2. Move into the directories",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 1734685060575,
                "content": "3. Create the project",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 1734685093151,
                "content": "npm create vite@latest . -- --template react-ts",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 3,
                "content": "npm install",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 1734685116127,
                "content": "4. Fix the tsconfig.app.json",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 1734685152055,
                "content": "4.1 To fix the \"tsBuildInfoFile\" problem, add this line before the \"tsBuildInfoFile\" line.",
                "completed": false,
                "listStyle": "text",
                "indent": 1
            },
            {
                "id": 1734685193126,
                "content": "\"incremental\": true,",
                "completed": false,
                "listStyle": "code",
                "indent": 2
            },
            {
                "id": 1734685219286,
                "content": "4.2 To fix the \"noUncheckedSideEffectImports\": true, just delete it.",
                "completed": false,
                "listStyle": "text",
                "indent": 1
            },
            {
                "id": 1734685152056,
                "content": "5. Install React router library.",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 1734685193127,
                "content": "npm install react-router-dom",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },,
            {
                "id": 1734685152058,
                "content": "6. For TypeScript, you also need the type declarations.",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 17346851931561,
                "content": "npm install --save-dev @types/react-router-dom",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 1734685152069,
                "content": "8. Put this code in main.tsx for routing purposes.",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 17346851125124,
                "content": 'import { BrowserRouter as Router, Routes, Route, Navigate } from "react-router-dom";\n\n<React.StrictMode>\n    <Router>\n        <Routes>\n            <Route path="/" element={ <Navigate to="/main" />} />\n            <Route path="/main" element={<App />} />\n        </Routes>\n    </Router>\n</React.StrictMode>',
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
        ],
        "completed": true,
        "priority": true,
        "schedule": false,
        "scheduleType": "",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "noDeadlineStartTime",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    },
    {
        "id": "I-0002",
        "title": "How to setup a TailwindCSS project ?",
        "description": "no description",
        "subTask": [
            {
                "id": 1734686180058,
                "content": "TailwindCSS",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 1734686210782,
                "content": "1. Install TailwindCSS",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 1734686234993,
                "content": "npm install -D tailwindcss postcss autoprefixer",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 1734686243774,
                "content": "2. Initialize the TailwindCSS configuration files",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 1734686251862,
                "content": "npx tailwindcss init -p",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 1734686264062,
                "content": "3. Configure the tailwind.config.js file to include Vite's content paths:",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 1734686272902,
                "content": "/** @type {import('tailwindcss').Config} */\nexport default {\n  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],\n  theme: {\n    extend: {},\n  },\n  plugins: [],\n};",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 1734686300623,
                "content": "4. Add the TailwindCSS base styles to your style sheet",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 1734686293894,
                "content": "@tailwind base;\n@tailwind components;\n@tailwind utilities;",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 21078213123,
                "content": "5. Start the Tailwind CLI build process",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 289412412412414,
                "content": "npx tailwindcss -i ./src/style/index.css -o ./src/style/output.css --watch",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 17345286211238,
                "content": "6. Start using Tailwind in your `main.tsx`",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 173468124124124,
                "content": "import './src/style/output.css';",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 1734125125,
                "content": "7. To fix the `Unknown at rule @tailwindcss(unknownAtRules)` problem",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 173461212421,
                "content": "npm install -D tailwindcss postcss autoprefixer",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 1734124573,
                "content": "8. Then reopen VSCode window",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
        ],
        "completed": true,
        "priority": true,
        "schedule": false,
        "scheduleType": "",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "noDeadlineStartTime",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    },
    {
        "id": "I-0003",
        "title": "How to setup a Bootstrap project ?",
        "description": "no description",
        "subTask": [
            {
                "id": 1734685323536,
                "content": "1. Install Bootstrap",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 4,
                "content": "npm install bootstrap",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 5,
                "content": "2. On main.tsx",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 6,
                "content": "import 'bootstrap/dist/css/bootstrap.min.css';",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 7,
                "content": "3. Override Bootstrap Var for more Customize Style",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 8,
                "content": "npm install sass",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 9,
                "content": "4. Create a file like src/styles/custom.scss and import Bootstrap",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 10,
                "content": "@import \"bootstrap/scss/bootstrap\";",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 11,
                "content": "5. Import the custom file in main.tsx instead of bootstrap.min.css",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 12,
                "content": "import './styles/custom.scss';",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 13,
                "content": "6. Install React Bootstrap components",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 14,
                "content": "npm install react-bootstrap bootstrap",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 15,
                "content": "import { Button, etc } from 'react-bootstrap';",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 16,
                "content": "7. Install Bootstrap Icons",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 17,
                "content": "npm install bootstrap-icons",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 18,
                "content": "import 'bootstrap-icons/font/bootstrap-icons.css';",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 19,
                "content": "8. Install React Icons",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 20,
                "content": "npm install react-icons",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 21,
                "content": "import { FaBeer } from 'react-icons/fa';",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 22,
                "content": "9. React Icons includes many popular libraries. You can import from these prefixes:",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 1734686570343,
                "content": "fa: Font Awesome\nmd: Material Design\nai: Ant Design\nbs: Bootstrap Icons\ngi: Game Icons\nio: Ionicons\nri: Remix Icons\nsi: Simple Icons\nfi: Feather Icons\ncg: CSS.gg\ntb: Tabler Icons",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            }
        ],
        "completed": true,
        "priority": true,
        "schedule": false,
        "scheduleType": "",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "noDeadlineStartTime",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    },
    {
        "id": "I-0004",
        "title": "How to setup a Vercel project ?",
        "description": "no description",
        "subTask": [
            {
                "id": 1734685323536,
                "content": '1. Make a "vercel.json" file',
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 4,
                "content": '{\n    \"routes\": [\n        {\n            \"src\": \"/[^.]+\",\n            \"dest\": \"/\"\n        }\n    ]\n}',
                "completed": false,
                "listStyle": "code",
                "indent": 1
            }
        ],
        "completed": true,
        "priority": true,
        "schedule": false,
        "scheduleType": "",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "noDeadlineStartTime",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    },
    {
        "id": "I-0005",
        "title": "How to install FontAwesome Icons ?",
        "description": "no description",
        "subTask": [
            {
                "id": 17346861800125,
                "content": "1. Install the Font Awesome Packages",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 17346861241,
                "content": "# Core Font Awesome package\nnpm install @fortawesome/fontawesome-svg-core\n\n# Free solid icons\nnpm install @fortawesome/free-solid-svg-icons\n\n# Free regular icons (optional, if you need them)\nnpm install @fortawesome/free-regular-svg-icons\n\n# React wrapper for Font Awesome\nnpm install @fortawesome/react-fontawesome",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
            {
                "id": 1734663574,
                "content": "2. Usage in a React Component",
                "completed": false,
                "listStyle": "text",
                "indent": 0
            },
            {
                "id": 17312451862,
                "content": "import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';\nimport { faCoffee } from '@fortawesome/free-solid-svg-icons';",
                "completed": false,
                "listStyle": "code",
                "indent": 1
            },
        ],
        "completed": true,
        "priority": true,
        "schedule": false,
        "scheduleType": "",
        "deadlineStartDate": "noDeadlineStartDate",
        "deadlineEndDate": "noDeadlineEndDate",
        "deadlineStartTime": "noDeadlineStartTime",
        "deadlineEndTime": "noDeadlineEndTime",
        "tags": []
    }
]